[project]
name = "ucm-gidia-pd2-amcf-ws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.3",
    "folium>=0.20.0",
    "geopandas>=1.1.3",
    "lightgbm>=4.6.0",
    "minio>=7.2.20",
    "pandas>=3.0.2",
    "plotly>=6.7.0",
    "pyarrow>=24.0.0",
    "scikit-learn>=1.8.0",
]
